export const API_ROOT = "https://janyl567.pythonanywhere.com/"
export const API_ESTABLISHNENTS = API_ROOT + "establishments/"
export const API_CATEGORIES = API_ROOT + "categories/"
export const API_QA = API_ROOT + "qa/"
export const API_FORMS = API_ROOT + "forms/"